// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DealerApi.Entities.Models;

public partial class CustomerTemp
{
    public int CustomerTempId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    // public bool IsGuest { get; set; }

    public string Address { get; set; }

    public string District { get; set; }

    public string Province { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

}